-- 定时任务批量删除优化

INSERT INTO activity (
    id,
    publisher_id,
    title,
    cover_url,
    content,
    location,
    venue_id,
    signup_start_time,
    signup_end_time,
    activity_start_time,
    activity_end_time,
    signup_limit,
    current_signup_count,
    wait_limit,
    status,
    audit_status,
    audit_remark,
    audit_user_id,
    audit_time,
    is_deleted
) VALUES (
             990001,
             1,
             'SCAN缓存删除测试活动',
             '/images/activity/poster-code.jpg',
             '用于测试定时任务触发活动状态流转后，是否通过SCAN删除活动详情缓存',
             '测试地点',
             1,
             DATE_SUB(NOW(), INTERVAL 1 MINUTE),
             DATE_ADD(NOW(), INTERVAL 10 MINUTE),
             DATE_ADD(NOW(), INTERVAL 30 MINUTE),
             DATE_ADD(NOW(), INTERVAL 60 MINUTE),
             100,
             0,
             10,
             1,
             1,
             '测试通过',
             1,
             NOW(),
             0
         );